version: "3.7"

services:
    db:
        image: postgres:latest
        restart: always
        environment:
<<<<<<< HEAD
            POSTGRES_DB: coracoes_da_lila
            POSTGRES_USER: lila
            POSTGRES_PASSWORD: lila

=======
            POSTGRES_DB: lila
            POSTGRES_USER: lila
            POSTGRES_PASSWORD: lila
>>>>>>> origin/US056-Carregarosdados
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
<<<<<<< HEAD

volumes:
    db-data:
=======
 
    pgadmin:
        image: dpage/pgadmin4:latest
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
            PGADMIN_DEFAULT_PASSWORD: lila
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "8090:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        links:
            - "db:pgsql-server"

volumes:
    db-data:
    pgadmin-data:
>>>>>>> origin/US056-Carregarosdados
